pipeline {
  agent any

  environment {
    DOCKER_IMAGE = "adityaxsolanki/aws-crime-syndicate:v2"
  }

  stages {
    stage('Clone Repository') {
      steps {
        echo "Cloning GitHub Repo 🔥"
        git branch: 'main', url: 'https://github.com/adityaxsolanki/aws-multi-tier-architecture.git'
      }
    }

    stage('Docker Build & Push') {
      steps {
        echo "Building Docker Image 🚀"
        withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
          sh '''
            docker build -t $DOCKER_IMAGE .
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push $DOCKER_IMAGE
          '''
        }
      }
    }

    stage('Deploy to Same Instance') {
      steps {
        echo "Deploying App on Same EC2 🔥"
        sh '''
          docker stop app || true
          docker rm app || true
          docker rmi $(docker images -f "dangling=true" -q) || true
          docker run -d --name app -p 7070:80 $DOCKER_IMAGE
        '''
      }
    }
  }

  post {
    success {
      echo "🚀 Pipeline Successful"
    }
    failure {
      echo "💀 Pipeline Failed"
    }
  }
}
