pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'docker build -t adityaxsolanki/aws-crime-syndicate:v1 -f ..docker/Dockerfile .'
            }
        }
        stage('Push') {
            steps {
                sh 'docker push adityaxsolanki/aws-crime-syndicate:v1'
            }
        }
    }
}
