pipeline {
  agent any

  environment {
    DOCKER_IMAGE = "adityaxsolanki/aws-crime-syndicate:v1"  // Dynamic tag based on build number
  }

  stages {
    stage('Clone Repository') {
      steps {
        echo "Cloning GitHub Repo 🔥"
        git branch: 'main', url: 'https://github.com/adityaxsolanki/aws-multi-tier-architecture.git'
      }
    }

    stage('Docker Build & Push') {
      steps {
        echo "Building Docker Image 🚀"
        sh '''
          docker build -t $DOCKER_IMAGE .
          docker login -u adityaxsolanki -p $DOCKER_PASSWORD
          docker push $DOCKER_IMAGE
        '''
      }
    }

    stage('Deploy to Same Instance') {
      steps {
        echo "Deploying App on Same EC2 🔥"
        sh '''
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 80:80 $DOCKER_IMAGE
        '''
      }
    }
  }

  post {
    success {
      echo "🚨 Pipeline Successful"
    }
    failure {
      echo "💀 Pipeline Failed"
    }
  }
}
